modLoader="javafml" #mandatory
loaderVersion="[28,)" #mandatory

[[mods]] #mandatory
	modId="snowmancy" #mandatory
	version="v1.0.2" #mandatory
	displayName="Snowmancy" #mandatory
	description='''Build your own snowman companion!''' #mandatory
	issueTrackerURL="https://github.com/bl4ckscor3/Snowmancy/issues"
	displayURL="http://minecraft.curseforge.com/projects/snowmancy"
	authors="bl4ckscor3"

[[dependencies.snowmancy]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowmancy]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14,1.15)"
    ordering="NONE"
    side="BOTH"