modLoader="javafml"
loaderVersion="[1,)"
license="MIT https://github.com/bl4ckscor3/Snowmancy/blob/1.20.4/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Snowmancy/issues"

[[mods]]
	modId="snowmancy"
	version="${file.jarVersion}"
	displayName="Snowmancy"
	description='''Build your own snowman companion!'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snowmancy"
	authors="bl4ckscor3"

[[dependencies.snowmancy]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.70-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowmancy]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4,1.21)"
    ordering="NONE"
    side="BOTH"