license="MIT https://github.com/bl4ckscor3/Snowmancy/blob/1.21.54/LICENSE"
issueTrackerURL="https://github.com/bl4ckscor3/Snowmancy/issues"

[[mods]]
	modId="snowmancy"
	version="${file.jarVersion}"
	displayName="Snowmancy"
	description='''Build your own snowman companion!'''
	displayURL="https://www.curseforge.com/minecraft/mc-mods/snowmancy"
	authors="bl4ckscor3"

[[mixins]]
    config="snowmancy.mixins.json"

[[dependencies.snowmancy]]
    modId="neoforge"
    type="required"
    versionRange="[21.5.11-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowmancy]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.5,1.22)"
    ordering="NONE"
    side="BOTH"